---
# Codes from GC naming doc, currently used for reference only
codes:
  SRV* : "Servers* - see server.yaml for codes."
  BST : "Bastion Host"
  FWL : "Firewall"
  ADC : "Application Delivery Controller"
  IDS : "Intrusion Detection System"
  IPS : "Intrusion Prevention System"
  RTR : "Router"
  XSW : "Network Switch"
  QFC : "Storage SAN Switch"
  VDI : "Virtual Desktop"
  CLD : "Generic Cloud Entity"
  CNR : "Cloud Network Resource"
  CSA : "Cloud Storage Account"
  CSV : "Cloud Secret Vault"
  CCR : "Cloud Container Registry"
  CPS : "Cloud Platform Service"
  CLD : "Generic Cloud Entity / Object"
  VSC : "VPC Service Controls object"
  ROL : "Custom Role"